=== valmynd/MediaFetcher/src/models/queue.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="queue">
		<xs:annotation>
			<xs:documentation>Schema used by both Clipboard- and DownloadModel</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="task">
					<xs:annotation>
						<xs:documentation>task elements are replaced as soon as information from the respective url is extracted</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:attribute name="url" type="xs:string" use="required"/>
						<xs:attribute name="status" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>may contain either failure notices or just 'Ready' or 'Avaiable'</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="item" type="itemType" maxOccurs="unbounded"/>
				<xs:element name="package" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" type="itemType" maxOccurs="unbounded"/>
						</xs:sequence>
						<xs:attribute name="name" use="required"/>
						<xs:attribute name="url" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>originally pasted url</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="itemType">
		<xs:sequence>
			<xs:element name="subtitle" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="language" type="xs:string" use="required"/>
					<xs:attribute name="url" type="xs:string">
						<xs:annotation>
							<xs:documentation>link to the subtitle file</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="format" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="option" maxOccurs="unbounded">
							<xs:complexType>
								<xs:attribute name="quality" type="xs:string" use="required">
									<xs:annotation>
										<xs:documentation>e.g. 720p</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="url" type="xs:string" use="required">
									<xs:annotation>
										<xs:documentation>link to the actual file</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="location" type="xs:string">
									<xs:annotation>
										<xs:documentation>Physical location of the video. (???)</xs:documentation>
									</xs:annotation>
								</xs:attribute>
								<xs:attribute name="player_url" type="xs:string">
									<xs:annotation>
										<xs:documentation>SWF Player URL (used for rtmpdump).</xs:documentation>
									</xs:annotation>
								</xs:attribute>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="extension" type="xs:string" use="required">
						<xs:annotation>
							<xs:documentation>file extension, e.g. flv</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="selected" type="xs:string">
						<xs:annotation>
							<xs:documentation>currently selected quality, e.g. 720p</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="title" type="xs:string" use="required"/>
		<xs:attribute name="url" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>originally pasted url</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="status" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>may contain either failure notices or just 'Ready' or 'Avaiable'</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="host" type="xs:string">
			<xs:annotation>
				<xs:documentation>name of the hoster</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="description" type="xs:string">
			<xs:annotation>
				<xs:documentation>description provided by the uploader (readonly)</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="thumbnail" type="xs:string">
			<xs:annotation>
				<xs:documentation>URL for thumbnail</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="selected" type="xs:string">
			<xs:annotation>
				<xs:documentation>currently selected format, e.g. flv</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="path">
			<xs:annotation>
				<xs:documentation>download path</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== valmynd/MediaFetcher/src/models/clipboard_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<queue xsi:noNamespaceSchemaLocation="queue.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <item title="Item 1" status="Available" url="somewhere">
        <subtitle language="English"/>
        <subtitle language="Danish"/>
        <format extension="mp4">
            <option quality="320*280" location="" url="url" player_url=""/>
            <option quality="720*480" location="" url="url" player_url=""/>
        </format>
    </item>
    <item title="Item 2" selected="webm" status="Available" url="somewhere">
        <subtitle language="English"/>
        <subtitle language="German"/>
        <format extension="mp4" selected="120*180">
            <option quality="320*280" location="" url="url" player_url=""/>
            <option quality="120*180" location="" url="url" player_url=""/>
            <option quality="720*480" location="" url="url" player_url=""/>
        </format>
        <format extension="webm" selected="120*180">
            <option quality="120*180" location="" url="url" player_url=""/>
            <option quality="1080*480" location="" url="url" player_url=""/>
        </format>
    </item>
    <package name="Youtube Playlist" url="somewhere">
        <item title="Item 3.1" status="Available" url="somewhere">
            <subtitle language="String"/>
            <subtitle language="String"/>
            <format extension="String">
                <option quality="320*280" location="" url="url" player_url=""/>
            </format>
            <format extension="String">
                <option quality="720*480" location="" url="url" player_url=""/>
            </format>
        </item>
        <item title="Item 3.2" status="Available" url="somewhere">
            <subtitle language="String"/>
            <subtitle language="String"/>
            <format extension="String">
                <option quality="320*280" location="" url="url" player_url=""/>
            </format>
            <format extension="String">
                <option quality="720*480" location="" url="url" player_url=""/>
            </format>
        </item>
    </package>
    <package name="Package 2" url="somewhere">
        <item title="Item 4.1" status="Available" url="somewhere">
            <subtitle language="String"/>
            <subtitle language="String"/>
            <format extension="String">
                <option quality="320*280" location="" url="url" player_url=""/>
            </format>
            <format extension="String">
                <option quality="720*480" location="" url="url" player_url=""/>
            </format>
        </item>
        <item title="Item 4.2" status="Available" url="somewhere">
            <subtitle language="String"/>
            <subtitle language="String"/>
            <format extension="String">
                <option quality="320*280" location="" url="url" player_url=""/>
            </format>
            <format extension="String">
                <option quality="720*480" location="" url="url" player_url=""/>
            </format>
        </item>
    </package>
</queue>
